# Generated by Django 3.1.4 on 2021-01-05 10:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='HealthFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=70)),
                ('county', models.CharField(max_length=35)),
                ('subcounty', models.CharField(max_length=40)),
                ('ward', models.CharField(max_length=40)),
                ('facility_type', models.CharField(choices=[('Clinic', 'Clinic'), ('Dispensary', 'Dispensary'), ('District Hospital', 'District Hospital'), ('Health Centre', 'Health Centre'), ('Misssion Hospital', 'Misssion Hospital'), ('National Referral Hospital', 'National Referral Hospital'), ('Provincial General Hospital', 'Provincial General Hospital'), ('Sub-District Hospital', 'Sub-District Hospital')], max_length=30)),
                ('ownership', models.CharField(choices=[('NGO', 'NGO'), ('FBO', 'FBO'), ('MoH', 'MoH'), ('Local Authority', 'Local Authority'), ('Private', 'Private')], max_length=15)),
                ('source', models.CharField(choices=[('GPS', 'GPS'), ('Google Earth', 'Google Earth'), ('Other', 'Other'), ('Geonames', 'Geonames')], max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Health Faclity',
                'verbose_name_plural': 'Health Facilities',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=35)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name=4326)),
            ],
        ),
        migrations.AddIndex(
            model_name='healthfacilities',
            index=models.Index(fields=['facility_name'], name='locator_hea_facilit_2e54a5_idx'),
        ),
    ]
